name: CHOICE CABINETRY
favicon: null
layout_spectrum: 0.358141707489267
typography_spectrum: 0.2863245678599924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#105da3'
    - '#bfd4e7'
    - '#5a8ebe'
    - '#f1c771'
  brandStrength: 0.9506234512664378
  lightness: 0.8058332444634289
  saturation: 0.23152403207495809
  rhythmicContrast: 0.8190134551841766
purpose: []
